### ISSUE TITLE
Switching Pages Breaks Widget Focus

### ISSUE THREAD

**Issue by DapperMongoose** [cogentcore/core#1322]
### Describe the bug

The new page switching is really nice, unfortunately it doesn't seem to play completely nicely with focus.  This may also be user error.

### How to reproduce

I ran this two ways to try and understand what was going on, first:

- Run example code (slightly modified from tutorial)
- Observe that the text box is focused as expected and styled to indicate that
- Enter a string and click sign in button
- Observe that the text box on the "home" page is not styled as focused
- Attempt to type some characters slowly one at a time
- Observe that the text box isn't actually focused for the first few key presses
- Click sign out button
- Observe that the text box is not styled as focused this time
- Attempt to type some characters slowly one at a time
- Observe that the text box isn't actually focused for the first few key presses

Second, swap to using SetFocusEvent instead by switching which lines are commented and then:

- Run example code
- Observe that the text box is not styled as focused
- Attempt to enter some characters
- Observe that text box is actually focused
- Click sign in button
- Observe that text box on "home" page is not styled as focused
- Attempt to type some characters
- Observe that the text box is actually focused
- Click sign out button
- Attempt to enter text once again, observing that once again the text box is actually focused but not styled as such

### Example code

```go
package main

import (
	"cogentcore.org/core/core"
	"cogentcore.org/core/events"
)

type user struct {
	Username string
}

func main() {
	b := core.NewBody()
	u := &user{}
	pg := core.NewPages(b)
	pg.AddPage("sign-in", func(pg *core.Pages) {
		userField := core.NewTextField(pg)
		userField.StartFocus()
		//userField.SetFocusEvent()
		core.NewButton(pg).SetText("Sign in").OnClick(func(e events.Event) {
			u.Username = userField.Text()
			pg.Open("home")
		})
	})
	pg.AddPage("home", func(pg *core.Pages) {
		core.NewText(pg).SetText("Welcome, " + u.Username + "!").SetType(core.TextHeadlineSmall)
		newField := core.NewTextField(pg)
		newField.StartFocus()
		//newField.SetFocusEvent()
		core.NewButton(pg).SetText("Sign out").OnClick(func(e events.Event) {
			*u = user{}
			pg.Open("sign-in")
		})
	})

	b.RunMainWindow()
}
```

### Platform

Linux

**Comment by kkoreilly** [comment]
Thank you for reporting this. The correct behavior here should definitely be possible. We will fix this issue, clean up the API, and add better documentation for focusing next Sunday.

**Comment by kkoreilly** [comment]
We fixed this in #1337, so you can get the correct behavior now using `StartFocus` in the first way you described. We also renamed `SetFocusEvent` to `SetFocus` (the old `SetFocus` is now `SetFocusQuiet`), which better represents the functionality. You could also now use `tf.Defer(tf.SetFocus)` to achieve a similar effect, but `StartFocus` is more idiomatic. I will document this new functionality on the website within a few days as part of my ongoing restructuring of the documentation (#1321).

**Comment by ghost** [comment]
I can confirm that StartFocus is now working correctly.  Worth noting that SetFocus is still not styling the text fields as focused.  I do like that it's now SetFocus since I did bump up against that confusion initially when I was trying to use it! :)

**Comment by kkoreilly** [comment]
Great! The reason that `SetFocus` does not work for styling the text fields is that they have not been initially styled yet, so they do not have the proper abilities to be focused yet. That is why you should use `StartFocus` for any element that has been newly created. `SetFocus` is intended for an already rendered element that you are now focusing after it was already shown. That is why `userField.Defer(userField.SetFocus)` also works: by using `Defer`, you are making it run after the widget has already been shown.

I realize that is not clear in the current documentation, and I will clarify that documentation within the next few days both in the API and on the website.

**Comment by kkoreilly** [comment]
@DapperMongoose This is now all documented on the website: https://www.cogentcore.org/core/events#set-focus. Please let me know if there are any issues. Thank you for your patience.
