### ISSUE TITLE
'Add' button shows through pop-up Props menu (top left)

### ISSUE THREAD

**Issue by thazy** [cogentcore/core#50]
![img_0155](https://user-images.githubusercontent.com/30027010/44592874-0e747b00-a77f-11e8-8645-927bd76aa50e.JPG)

**Comment by rcoreilly** [comment]
I think I've fixed this -- I can't reproduce -- can you try it again with the latest checkin (just git pull and go build in gi/examples).  Maybe also fixes some of the other instability you've been seeing?  there was some bad code there with those toolbars (where Add lives).

**Comment by thazy** [comment]
Even after git pull and go build the ‘Add’ is still showing through for me immediately upon clicking the Props button; as soon as I move cursor to that menu window and scroll it goes away.

On Aug 24, 2018, at 2:50 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I've fixed this -- I can't reproduce -- can you try it again with the latest checkin (just git pull and go build in gi/examples). Maybe also fixes some of the other instability you've been seeing? there was some bad code there with those toolbars (where Add lives).

**Comment by rcoreilly** [comment]
Ok, I figured out how to reproduce this -- you need to have the props window sized just right so that the props widget indicator is scrolled off-screen, which then causes the popup to show up on the left like that.  immediate fix is to have the popup show up in the right place.  will take a look.
